config/routes.rb
Rails.application.routes.draw do

  get 'streams/new'

  get 'streams/create'

  get 'streams/update'

  get 'streams/edit'

  get 'streams/destroy'

  resources :recordings

  resources :streams

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

  get 'db_manage' => 'dbmanage#db_manage'

  get 'help' => 'static_pages#help'

  get 'home' => 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
 
  post   'login'   => 'sessions#create'

  delete 'logout'  => 'sessions#destroy'

  get 'addnetwork' => 'networks#new'

  get 'maps' => 'maps#show'

  resources :devices

  resources :networks

  resources :networks do
    resources :devices
  end

  resources :networks do
    resources :users
  end

  resources :users do
    resources :networks
  end

  get :startaudiostream, controller:"streams"

  get :startlistener, controller:"streams"

  get :tunnelToMasterFrom6, controller:"streams"

  get :Stream6Broadcasting, controller:"streams"

  get :ForwardStreamThroughNode, controller:"streams"

  get :StreamReceiving, controller:"streams"

  resources :users
  
  resources :microposts #,          only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]

  resources :comments

end

app/models/network.rb
class Network < ActiveRecord::Base
  enum audience: [ :restricted, :open ]

  validates :name,  presence: true, length: { maximum: 50 }

  has_and_belongs_to_many :users

  validates :publickey, presence:true, :unless => '!private?'

  has_many :devices, dependent: :destroy

  has_many :microposts, dependent: :destroy
  has_many :users
  belongs_to :admin, :class_name => 'User'
  before_create { self.id = rand(1000..9999)}
  has_many :streams

  enum key_type:  [:rsa, :dsa, :ecdsa, :drop_bear]

  belongs_to :admin, class_name: "User"



end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
 
def say
@network = Network.find(params[:id])
 @devices = @network.devices.all 
 @hash = Gmaps4rails.build_markers(@network.devices) do |device, marker| 
 marker.lat device.latitude 
 marker.lng device.longitude 
 marker.picture({"url" => "https://lh3.googleusercontent.com/YKh2bl1P53SCWfZplfmP5rpKDQIAiJAQCqLnFSXFUy8eMV5UOZW8YJiy7HHShH-qoMH7PwKSwo8=s50-h50-e365","width" =>  50,"height" => 50}) 
 marker.json({:id => device.id }) 
 marker.infowindow render device 
end
end


  def new
    @network = Network.new
  end

  def show
   @network = Network.find(params[:id])
   @devices = @network.devices.all
   @mic_ids = @network.micropost_ids
   if logged_in?
   @feed1 = Micropost.where(user_id: current_user.id)
   @feed2 = Micropost.where(private: false)
   @feed3 = Micropost.where(network: current_user.networks)
   @feed= @feed1.merge(@feed2).merge(@feed3)




   end
       #current_user.feed.paginate(page: params[:page])
   #@hash = Gmaps4rails.build_markers(@network.devices)
  end

  def create
     @network = Network.new(network_params)
     @network.build(:admin_id => current_user.id )
     if @network.save
       flash[:success] = "Network added!"
       redirect_to @network
     else
       flash[:danger] = "Network failed to add!"
      render 'new'
    end
  end

def edit
  @network = Network.find(params[:id])
end

def update
  @network = Network.find(params[:id])
  if @network.update_attributes(network_params)
    flash[:success] = "Network updated!"
    redirect_to @network
  else
    render 'edit'
  end
end

  def index
    @networks = Network.paginate(page: params[:page])
    @devices = Device.all
    @network_array = @networks.all.map { |network| [network.name, network.id] }
  end

  def destroy
    @network = Network.find(params[:id])
    @network.destroy
    flash[:danger] = "network deleted"
    redirect_to request.referrer || root_url
  end

  def join
    Network.find(params).add_user.(params)

  end


  private

  def network_params
    params.require(:network).permit(:name, :publickey, :admin_id, :ssh_key, :private, :key_type)
  end

end

app/helpers/networks_helper.rb
module NetworksHelper
def marker_info(marker) 
 @network = Network.find(params[:id]) 
 @devices = @network.devices.all 
 @hash = Gmaps4rails.build_markers(@network.devices) do |device, marker| 
 marker.lat device.latitude 
 marker.lng device.longitude 
 marker.picture({"url" => "https://lh3.googleusercontent.com/YKh2bl1P53SCWfZplfmP5rpKDQIAiJAQCqLnFSXFUy8eMV5UOZW8YJiy7HHShH-qoMH7PwKSwo8=s50-h50-e365","width" =>  50,"height" => 50}) 
 marker.json({:id => device.id }) 
 marker.infowindow render device 
 end 
end
end

app/views/networks/_network.html.erb
<div class="jumbotron" style="color:black; padding-top: 5px; padding-left:5px; padding-right:5px" >
  <div class="container">

<h3 id="network <%= network.id %>">

  <% if logged_in? %>
        <h1>
      <%= link_to network.name, network %> <br>
        </h1>
      <%# if !@network.device_id.nil? %>

          <%# render map %>

      <%# end %>

      <% if network.devices.none? %>

          <li class="dropdown-header"> <h4> NO DEVICES FOUND, ADD A DEVICE?

          <%= button_to "Add New Device", {:controller => :devices, :action => :new, :network_id => network.id},
                        :method => 'get' %>

          </h4> </li>
      <% end %>



      <%= button_to "Edit Network?", edit_network_path(network.id), :method => :get %>

  <%= render @feed %>
      <% end %>

  <h2>


    ssh key : </h2><br>


  <div style="width:545px;overflow:auto;margin:auto">
    <pre>  <%= network.ssh_key %> </pre>
  </div>

  <br> <hr>






  <h2>


          public key : </h2><br>


          <div style="width:545px;overflow:auto;margin:auto">
           <pre>  <%= network.publickey %> </pre>
            </div>

  <br> <hr>

      <%= link_to network.name, network %> | total devices : <%=  link_to "total devices : " +
            network.devices.count.to_s, network_path(network, anchor: "devices")  %>

      <%= button_to "Add New Device", {:controller => :devices, :action => :new, :network_id => network.id},
                                       :method => 'get' %>
      <%= link_to "delete", network, method: :delete,
                  data: { confirm: "You sure?" } %>

    <h4>

      <!--<div id="devices">-->

      <h3>  Registered Devices </h3>

      <%= render network.devices %>


      <!--</div>-->

    </h4>
</h3>

      </div>
    </div>

app/views/networks/_network_form.html.erb
<%= form_for(@network, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@network) do |f| %>

            <%#= f.label :admin_id %>
            <%= f.hidden_field(:admin_id, :value => current_user.id) %>

            <%= f.label :name %>
            <%= f.text_field :name %>

            <%= f.label :publickey %>

            <%= f.text_area :publickey %>

            <%= f.label :ssh_key %>

            <%= f.text_area :ssh_key %>

            <%#= f.input :key_type, as: :select, collection: Network.key_types.keys %>

            <%#= f.collection_select(:key_type, Network.key_types.keys, :print, :print) %>

            <%= f.select :key_type, Network.key_types.keys %>


            <%= f.submit "Add Network", class: "btn btn-primary" %>

            Would you like this network to be private?
            (this will restrict post viewers to only people who are in the network.
            <%= f.check_box :private %>

        <% end %>

      </div>
<% end %>

</div>

app/views/networks/edit.html.erb
<% provide(:title, 'Add Network') %>
<h1>Edit Network</h1>

<%= render 'network_form' %>

app/views/networks/index.html.erb
<% provide(:title, 'All Networks') %>

<div class="col-lg col-sm-5">
<div class="row">
  <div class ="form-group">

<li class="dropdown-header"> SEARCH FOR TEXT </li>

<div class="col-lg-6">
  <div class="input-group">

    <input type="text" class="form-control" placeholder="Search for...">
      <span class="input-group-btn">

        <button class="btn btn-default" type="button">Go!</button>
      </span>
    </div>
  </div>



    <!--<div class="col-lg-6">-->
    <!--<div class="input-group">-->
    <!--</div>&lt;!&ndash; /.row &ndash;&gt;-->
  <!--</div>-->


<!--<div class="col-sm-offset-0 col-sm-0">-->

<!--</div>-->






     <!-- /input-group -->
  <!--</div>&lt;!&ndash; /.col-lg-6 &ndash;&gt;-->

  </div>


</div>


  </div>
<div class="col-lg col-sm-offset-10">
  <!--<div class="input-group">-->
  <li class="dropdown-header"> REGISTER NETWORK </li>
  <%= link_to "Add New Network", addnetwork_path, class: "btn btn-primary btn-default" %>
  </div>



<!--<%#= form_tag("/search", method: "get", class: "alight-left") do %>-->
    <!--<%#= label_tag(:q, "Search for:") %>-->




    <%#= text_field_tag(:q) %> <br>


    <!--<%#= button_to("Search", @networks_path, class: "form-control" ) %>-->





      <!--</div>-->

        <!--<div>-->

      <!--</div>-->
<!--<%# end %>-->
<!--</h4>-->

<h1><bold> Explore Networks </bold></h1>

 <%=  "Total Registered Networks : " +  @networks.count.to_s  %>

<ul class="networks">
<% @networks.each do |network| %>
<%#= "Network Name: " + link_to(network.name, path_to_asset(Network.find(network.id))) %>
 Network Name:  <%= link_to(network.name, network) %>

      <% if logged_in? %>


      <%# @devices = network.devices.all %>
      <% @feed = Micropost.where("user_id IN (?) OR user_id = ? OR network_id =?",
                                 network.micropost_ids, current_user.id, network.id)%>

      <%= render network %>



          <% end %>

      <br>
<% end %>
</ul>





<%#= will_paginate %>





<!--<ul class="networks">-->
  <!--<%# @networks.each do |network| %>-->
      <!--<%#= render @networks %>-->
  <!--<%# end %>-->
<!--</ul>-->

<%#= will_paginate %>

app/views/networks/new.html.erb
<% provide(:title, 'Add Network') %>
<h1>Add Network</h1>

<%= render 'network_form' %>

<%#= render 'shared/micropost_form' %>

</div>

app/views/networks/show.html.erb
<% provide(:title, @network.name) %>

  <% if @network.devices.any? %>

  <%= render 'shared/map' %>

  <% end %>

<%= render @network %>

<div id="devices">

<!--<div class="col-md-8">-->
  <% if @network.devices.any? %>
      <h2> Number of Devices : <%= @network.devices.count %></h2>
      <br> <hr>
      </div>

      <%= render @devices %>

      <%#= will_paginate @devices %>
  <% end %>